## Adopted from https://github.com/geerlingguy/ansible-role-solr/

- include: user.yml

- name: Check if Solr has been installed already.
  stat:
    path: "{{ solr_install_path }}"
  register: solr_install_path_status

- name: Download Solr.
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: false
  when: solr_install_path_status.stat.isdir is not defined
  register: solr_download_status

- name: Expand Solr.
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}"
    copy: false
  when: solr_download_status.changed

- include: install.yml

- name: Ensure solr is started and enabled on boot 
  service:
    name: "{{ solr_service_name }}"
    state: "started"
    enabled: true

- include: configure.yml
- include: cores.yml

# - include: cleanup.yml







# - name: Apply Solr configuration changes.
#   lineinfile:
#     dest: "{{ solr_config_file }}"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     state: present
#   with_items:
#     - regexp: "^.?SOLR_JAVA_MEM="
#       line: 'SOLR_JAVA_MEM="-Xms{{ solr_xms }} -Xmx{{ solr_xmx }}"'
#     - regexp: "^SOLR_PORT="
#       line: 'SOLR_PORT="{{ solr_port }}"'
#     - regexp: "^.?SOLR_TIMEZONE="
#       line: 'SOLR_TIMEZONE="{{ solr_timezone }}"'
#   notify: restart solr